class CountryCodes {


    static get MAP() {
        return {
            AF: { code: "AF", country: "Afghanistan" },
            AX: { code: "AX", country: "Åland Islands" },
            AL: { code: "AL", country: "Albania" },
            DZ: { code: "DZ", country: "Algeria" },
            AS: { code: "AS", country: "American Samoa" },
            AD: { code: "AD", country: "Andorra" },
            AO: { code: "AO", country: "Angola" },
            AI: { code: "AI", country: "Anguilla" },
            AQ: { code: "AQ", country: "Antarctica" },
            AG: { code: "AG", country: "Antigua and Barbuda" },
            AR: { code: "AR", country: "Argentina" },
            AM: { code: "AM", country: "Armenia" },
            AW: { code: "AW", country: "Aruba" },
            AU: { code: "AU", country: "Australia" },
            AT: { code: "AT", country: "Austria" },
            AZ: { code: "AZ", country: "Azerbaijan" },
            BS: { code: "BS", country: "Bahamas" },
            BH: { code: "BH", country: "Bahrain" },
            BD: { code: "BD", country: "Bangladesh" },
            BB: { code: "BB", country: "Barbados" },
            BY: { code: "BY", country: "Belarus" },
            BE: { code: "BE", country: "Belgium" },
            BZ: { code: "BZ", country: "Belize" },
            BJ: { code: "BJ", country: "Benin" },
            BM: { code: "BM", country: "Bermuda" },
            BT: { code: "BT", country: "Bhutan" },
            BO: { code: "BO", country: "Bolivia, Plurinational State of" },
            BQ: { code: "BQ", country: "Bonaire, Sint Eustatius and Saba" },
            BA: { code: "BA", country: "Bosnia and Herzegovina" },
            BW: { code: "BW", country: "Botswana" },
            BV: { code: "BV", country: "Bouvet Island" },
            BR: { code: "BR", country: "Brazil" },
            IO: { code: "IO", country: "British Indian Ocean Territory" },
            BN: { code: "BN", country: "Brunei Darussalam" },
            BG: { code: "BG", country: "Bulgaria" },
            BF: { code: "BF", country: "Burkina Faso" },
            BI: { code: "BI", country: "Burundi" },
            KH: { code: "KH", country: "Cambodia" },
            CM: { code: "CM", country: "Cameroon" },
            CA: { code: "CA", country: "Canada" },
            CV: { code: "CV", country: "Cape Verde" },
            KY: { code: "KY", country: "Cayman Islands" },
            CF: { code: "CF", country: "Central African Republic" },
            TD: { code: "TD", country: "Chad" },
            CL: { code: "CL", country: "Chile" },
            CN: { code: "CN", country: "China" },
            CX: { code: "CX", country: "Christmas Island" },
            CC: { code: "CC", country: "Cocos (Keeling) Islands" },
            CO: { code: "CO", country: "Colombia" },
            KM: { code: "KM", country: "Comoros" },
            CG: { code: "CG", country: "Congo" },
            CD: { code: "CD", country: "Congo, the Democratic Republic of the" },
            CK: { code: "CK", country: "Cook Islands" },
            CR: { code: "CR", country: "Costa Rica" },
            CI: { code: "CI", country: "Côte d'Ivoire" },
            HR: { code: "HR", country: "Croatia" },
            CU: { code: "CU", country: "Cuba" },
            CW: { code: "CW", country: "Curaçao" },
            CY: { code: "CY", country: "Cyprus" },
            CZ: { code: "CZ", country: "Czech Republic" },
            DK: { code: "DK", country: "Denmark" },
            DJ: { code: "DJ", country: "Djibouti" },
            DM: { code: "DM", country: "Dominica" },
            DO: { code: "DO", country: "Dominican Republic" },
            EC: { code: "EC", country: "Ecuador" },
            EG: { code: "EG", country: "Egypt" },
            SV: { code: "SV", country: "El Salvador" },
            GQ: { code: "GQ", country: "Equatorial Guinea" },
            ER: { code: "ER", country: "Eritrea" },
            EE: { code: "EE", country: "Estonia" },
            ET: { code: "ET", country: "Ethiopia" },
            FK: { code: "FK", country: "Falkland Islands (Malvinas)" },
            FO: { code: "FO", country: "Faroe Islands" },
            FJ: { code: "FJ", country: "Fiji" },
            FI: { code: "FI", country: "Finland" },
            FR: { code: "FR", country: "France" },
            GF: { code: "GF", country: "French Guiana" },
            PF: { code: "PF", country: "French Polynesia" },
            TF: { code: "TF", country: "French Southern Territories" },
            GA: { code: "GA", country: "Gabon" },
            GM: { code: "GM", country: "Gambia" },
            GE: { code: "GE", country: "Georgia" },
            DE: { code: "DE", country: "Germany" },
            GH: { code: "GH", country: "Ghana" },
            GI: { code: "GI", country: "Gibraltar" },
            GR: { code: "GR", country: "Greece" },
            GL: { code: "GL", country: "Greenland" },
            GD: { code: "GD", country: "Grenada" },
            GP: { code: "GP", country: "Guadeloupe" },
            GU: { code: "GU", country: "Guam" },
            GT: { code: "GT", country: "Guatemala" },
            GG: { code: "GG", country: "Guernsey" },
            GN: { code: "GN", country: "Guinea" },
            GW: { code: "GW", country: "Guinea-Bissau" },
            GY: { code: "GY", country: "Guyana" },
            HT: { code: "HT", country: "Haiti" },
            HM: { code: "HM", country: "Heard Island and McDonald Islands" },
            VA: { code: "VA", country: "Holy See (Vatican City State)" },
            HN: { code: "HN", country: "Honduras" },
            HK: { code: "HK", country: "Hong Kong" },
            HU: { code: "HU", country: "Hungary" },
            IS: { code: "IS", country: "Iceland" },
            IN: { code: "IN", country: "India" },
            ID: { code: "ID", country: "Indonesia" },
            IR: { code: "IR", country: "Iran, Islamic Republic of" },
            IQ: { code: "IQ", country: "Iraq" },
            IE: { code: "IE", country: "Ireland" },
            IM: { code: "IM", country: "Isle of Man" },
            IL: { code: "IL", country: "Israel" },
            IT: { code: "IT", country: "Italy" },
            JM: { code: "JM", country: "Jamaica" },
            JP: { code: "JP", country: "Japan" },
            JE: { code: "JE", country: "Jersey" },
            JO: { code: "JO", country: "Jordan" },
            KZ: { code: "KZ", country: "Kazakhstan" },
            KE: { code: "KE", country: "Kenya" },
            KI: { code: "KI", country: "Kiribati" },
            KP: { code: "KP", country: "Korea, Democratic People's Republic of" },
            KR: { code: "KR", country: "Korea, Republic of" },
            KW: { code: "KW", country: "Kuwait" },
            KG: { code: "KG", country: "Kyrgyzstan" },
            LA: { code: "LA", country: "Lao People's Democratic Republic" },
            LV: { code: "LV", country: "Latvia" },
            LB: { code: "LB", country: "Lebanon" },
            LS: { code: "LS", country: "Lesotho" },
            LR: { code: "LR", country: "Liberia" },
            LY: { code: "LY", country: "Libya" },
            LI: { code: "LI", country: "Liechtenstein" },
            LT: { code: "LT", country: "Lithuania" },
            LU: { code: "LU", country: "Luxembourg" },
            MO: { code: "MO", country: "Macao" },
            MK: { code: "MK", country: "Macedonia, the Former Yugoslav Republic of" },
            MG: { code: "MG", country: "Madagascar" },
            MW: { code: "MW", country: "Malawi" },
            MY: { code: "MY", country: "Malaysia" },
            MV: { code: "MV", country: "Maldives" },
            ML: { code: "ML", country: "Mali" },
            MT: { code: "MT", country: "Malta" },
            MH: { code: "MH", country: "Marshall Islands" },
            MQ: { code: "MQ", country: "Martinique" },
            MR: { code: "MR", country: "Mauritania" },
            MU: { code: "MU", country: "Mauritius" },
            YT: { code: "YT", country: "Mayotte" },
            MX: { code: "MX", country: "Mexico" },
            FM: { code: "FM", country: "Micronesia, Federated States of" },
            MD: { code: "MD", country: "Moldova, Republic of" },
            MC: { code: "MC", country: "Monaco" },
            MN: { code: "MN", country: "Mongolia" },
            ME: { code: "ME", country: "Montenegro" },
            MS: { code: "MS", country: "Montserrat" },
            MA: { code: "MA", country: "Morocco" },
            MZ: { code: "MZ", country: "Mozambique" },
            MM: { code: "MM", country: "Myanmar" },
            NA: { code: "NA", country: "Namibia" },
            NR: { code: "NR", country: "Nauru" },
            NP: { code: "NP", country: "Nepal" },
            NL: { code: "NL", country: "Netherlands" },
            NC: { code: "NC", country: "New Caledonia" },
            NZ: { code: "NZ", country: "New Zealand" },
            NI: { code: "NI", country: "Nicaragua" },
            NE: { code: "NE", country: "Niger" },
            NG: { code: "NG", country: "Nigeria" },
            NU: { code: "NU", country: "Niue" },
            NF: { code: "NF", country: "Norfolk Island" },
            MP: { code: "MP", country: "Northern Mariana Islands" },
            NO: { code: "NO", country: "Norway" },
            OM: { code: "OM", country: "Oman" },
            PK: { code: "PK", country: "Pakistan" },
            PW: { code: "PW", country: "Palau" },
            PS: { code: "PS", country: "Palestine, State of" },
            PA: { code: "PA", country: "Panama" },
            PG: { code: "PG", country: "Papua New Guinea" },
            PY: { code: "PY", country: "Paraguay" },
            PE: { code: "PE", country: "Peru" },
            PH: { code: "PH", country: "Philippines" },
            PN: { code: "PN", country: "Pitcairn" },
            PL: { code: "PL", country: "Poland" },
            PT: { code: "PT", country: "Portugal" },
            PR: { code: "PR", country: "Puerto Rico" },
            QA: { code: "QA", country: "Qatar" },
            RE: { code: "RE", country: "Réunion" },
            RO: { code: "RO", country: "Romania" },
            RU: { code: "RU", country: "Russian Federation" },
            RW: { code: "RW", country: "Rwanda" },
            BL: { code: "BL", country: "Saint Barthélemy" },
            SH: { code: "SH", country: "Saint Helena, Ascension and Tristan da Cunha" },
            KN: { code: "KN", country: "Saint Kitts and Nevis" },
            LC: { code: "LC", country: "Saint Lucia" },
            MF: { code: "MF", country: "Saint Martin (French part)" },
            PM: { code: "PM", country: "Saint Pierre and Miquelon" },
            VC: { code: "VC", country: "Saint Vincent and the Grenadines" },
            WS: { code: "WS", country: "Samoa" },
            SM: { code: "SM", country: "San Marino" },
            ST: { code: "ST", country: "Sao Tome and Principe" },
            SA: { code: "SA", country: "Saudi Arabia" },
            SN: { code: "SN", country: "Senegal" },
            RS: { code: "RS", country: "Serbia" },
            SC: { code: "SC", country: "Seychelles" },
            SL: { code: "SL", country: "Sierra Leone" },
            SG: { code: "SG", country: "Singapore" },
            SX: { code: "SX", country: "Sint Maarten (Dutch part)" },
            SK: { code: "SK", country: "Slovakia" },
            SI: { code: "SI", country: "Slovenia" },
            SB: { code: "SB", country: "Solomon Islands" },
            SO: { code: "SO", country: "Somalia" },
            ZA: { code: "ZA", country: "South Africa" },
            GS: { code: "GS", country: "South Georgia and the South Sandwich Islands" },
            SS: { code: "SS", country: "South Sudan" },
            ES: { code: "ES", country: "Spain" },
            LK: { code: "LK", country: "Sri Lanka" },
            SD: { code: "SD", country: "Sudan" },
            SR: { code: "SR", country: "Suriname" },
            SJ: { code: "SJ", country: "Svalbard and Jan Mayen" },
            SZ: { code: "SZ", country: "Swaziland" },
            SE: { code: "SE", country: "Sweden" },
            CH: { code: "CH", country: "Switzerland" },
            SY: { code: "SY", country: "Syrian Arab Republic" },
            TW: { code: "TW", country: "Taiwan, Province of China" },
            TJ: { code: "TJ", country: "Tajikistan" },
            TZ: { code: "TZ", country: "Tanzania, United Republic of" },
            TH: { code: "TH", country: "Thailand" },
            TL: { code: "TL", country: "Timor-Leste" },
            TG: { code: "TG", country: "Togo" },
            TK: { code: "TK", country: "Tokelau" },
            TO: { code: "TO", country: "Tonga" },
            TT: { code: "TT", country: "Trinidad and Tobago" },
            TN: { code: "TN", country: "Tunisia" },
            TR: { code: "TR", country: "Turkey" },
            TM: { code: "TM", country: "Turkmenistan" },
            TC: { code: "TC", country: "Turks and Caicos Islands" },
            TV: { code: "TV", country: "Tuvalu" },
            UG: { code: "UG", country: "Uganda" },
            UA: { code: "UA", country: "Ukraine" },
            AE: { code: "AE", country: "United Arab Emirates" },
            GB: { code: "GB", country: "United Kingdom" },
            US: { code: "US", country: "United States" },
            UM: { code: "UM", country: "United States Minor Outlying Islands" },
            UY: { code: "UY", country: "Uruguay" },
            UZ: { code: "UZ", country: "Uzbekistan" },
            VU: { code: "VU", country: "Vanuatu" },
            VE: { code: "VE", country: "Venezuela, Bolivarian Republic of" },
            VN: { code: "VN", country: "Viet Nam" },
            VG: { code: "VG", country: "Virgin Islands, British" },
            VI: { code: "VI", country: "Virgin Islands, U.S." },
            WF: { code: "WF", country: "Wallis and Futuna" },
            EH: { code: "EH", country: "Western Sahara" },
            YE: { code: "YE", country: "Yemen" },
            ZM: { code: "ZM", country: "Zambia" },
            ZW: { code: "ZW", country: "Zimbabwe" }
        }
    }

    /**
     * Get a specific country by the code
     * @param code the code to get
     * @return {*} the country definition, or null
     */
    static get(code) {
        return CountryCodes.MAP[code];
    }

    /**
     * Get a list of countries
     * @return {Array} an array of country object definitions
     */
    static list() {
        let list = [];
        for (let c of Object.values(CountryCodes.MAP)) {
            list.push(c);
        }
        list.sort(function(a,b){
            if (a.country > b.country) { return 1 }
            if (a.country < b.country) { return -1 }
            return 0;
        });
        return list;
    }

}