class TimezoneDB {


    /**
     * Get the dictionary of the timezones.
     * @return a dictionary.
     */
    static get MAP() {
        return {
            "Asia/Kabul": { id: "Asia/Kabul", countrycode: "AF", country: "Afghanistan", tz: "Asia/Kabul", offset: "UTC +04:30" },
            "Europe/Tirane": { id: "Europe/Tirane", countrycode: "AL", country: "Albania", tz: "Europe/Tirane", offset: "UTC +01:00" },
            "Africa/Algiers": { id: "Africa/Algiers", countrycode: "DZ", country: "Algeria", tz: "Africa/Algiers", offset: "UTC +01:00" },
            "Pacific/Pago_Pago": { id: "Pacific/Pago_Pago", countrycode: "AS", country: "American Samoa", tz: "Pacific/Pago_Pago", offset: "UTC -11:00" },
            "Europe/Andorra": { id: "Europe/Andorra", countrycode: "AD", country: "Andorra", tz: "Europe/Andorra", offset: "UTC +01:00" },
            "Africa/Luanda": { id: "Africa/Luanda", countrycode: "AO", country: "Angola", tz: "Africa/Luanda", offset: "UTC +01:00" },
            "America/Anguilla": { id: "America/Anguilla", countrycode: "AI", country: "Anguilla", tz: "America/Anguilla", offset: "UTC -04:00" },
            "Antarctica/Casey": { id: "Antarctica/Casey", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/Casey", offset: "UTC +08:00" },
            "Antarctica/Davis": { id: "Antarctica/Davis", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/Davis", offset: "UTC +07:00" },
            "Antarctica/DumontDUrville": { id: "Antarctica/DumontDUrville", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/DumontDUrville", offset: "UTC +10:00" },
            "Antarctica/Mawson": { id: "Antarctica/Mawson", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/Mawson", offset: "UTC +05:00" },
            "Antarctica/McMurdo": { id: "Antarctica/McMurdo", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/McMurdo", offset: "UTC +13:00" },
            "Antarctica/Palmer": { id: "Antarctica/Palmer", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/Palmer", offset: "UTC -03:00" },
            "Antarctica/Rothera": { id: "Antarctica/Rothera", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/Rothera", offset: "UTC -03:00" },
            "Antarctica/Syowa": { id: "Antarctica/Syowa", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/Syowa", offset: "UTC +03:00" },
            "Antarctica/Troll": { id: "Antarctica/Troll", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/Troll", offset: "UTC" },
            "Antarctica/Vostok": { id: "Antarctica/Vostok", countrycode: "AQ", country: "Antarctica", tz: "Antarctica/Vostok", offset: "UTC +06:00" },
            "America/Antigua": { id: "America/Antigua", countrycode: "AG", country: "Antigua and Barbuda", tz: "America/Antigua", offset: "UTC -04:00" },
            "America/Argentina/Buenos_Aires": { id: "America/Argentina/Buenos_Aires", countrycode: "AR", country: "Argentina", tz: "America/Argentina/Buenos_Aires", offset: "UTC -03:00" },
            "America/Argentina/Catamarca": { id: "America/Argentina/Catamarca", countrycode: "AR", country: "Argentina", tz: "America/Argentina/Catamarca", offset: "UTC -03:00" },
            "America/Argentina/Cordoba": { id: "America/Argentina/Cordoba", countrycode: "AR", country: "Argentina", tz: "America/Argentina/Cordoba", offset: "UTC -03:00" },
            "America/Argentina/Jujuy": { id: "America/Argentina/Jujuy", countrycode: "AR", country: "Argentina", tz: "America/Argentina/Jujuy", offset: "UTC -03:00" },
            "America/Argentina/La_Rioja": { id: "America/Argentina/La_Rioja", countrycode: "AR", country: "Argentina", tz: "America/Argentina/La_Rioja", offset: "UTC -03:00" },
            "America/Argentina/Mendoza": { id: "America/Argentina/Mendoza", countrycode: "AR", country: "Argentina", tz: "America/Argentina/Mendoza", offset: "UTC -03:00" },
            "America/Argentina/Rio_Gallegos": { id: "America/Argentina/Rio_Gallegos", countrycode: "AR", country: "Argentina", tz: "America/Argentina/Rio_Gallegos", offset: "UTC -03:00" },
            "America/Argentina/Salta": { id: "America/Argentina/Salta", countrycode: "AR", country: "Argentina", tz: "America/Argentina/Salta", offset: "UTC -03:00" },
            "America/Argentina/San_Juan": { id: "America/Argentina/San_Juan", countrycode: "AR", country: "Argentina", tz: "America/Argentina/San_Juan", offset: "UTC -03:00" },
            "America/Argentina/San_Luis": { id: "America/Argentina/San_Luis", countrycode: "AR", country: "Argentina", tz: "America/Argentina/San_Luis", offset: "UTC -03:00" },
            "America/Argentina/Tucuman": { id: "America/Argentina/Tucuman", countrycode: "AR", country: "Argentina", tz: "America/Argentina/Tucuman", offset: "UTC -03:00" },
            "America/Argentina/Ushuaia": { id: "America/Argentina/Ushuaia", countrycode: "AR", country: "Argentina", tz: "America/Argentina/Ushuaia", offset: "UTC -03:00" },
            "Asia/Yerevan": { id: "Asia/Yerevan", countrycode: "AM", country: "Armenia", tz: "Asia/Yerevan", offset: "UTC +04:00" },
            "America/Aruba": { id: "America/Aruba", countrycode: "AW", country: "Aruba", tz: "America/Aruba", offset: "UTC -04:00" },
            "Antarctica/Macquarie": { id: "Antarctica/Macquarie", countrycode: "AU", country: "Australia", tz: "Antarctica/Macquarie", offset: "UTC +11:00" },
            "Australia/Adelaide": { id: "Australia/Adelaide", countrycode: "AU", country: "Australia", tz: "Australia/Adelaide", offset: "UTC +10:30" },
            "Australia/Brisbane": { id: "Australia/Brisbane", countrycode: "AU", country: "Australia", tz: "Australia/Brisbane", offset: "UTC +10:00" },
            "Australia/Broken_Hill": { id: "Australia/Broken_Hill", countrycode: "AU", country: "Australia", tz: "Australia/Broken_Hill", offset: "UTC +10:30" },
            "Australia/Currie": { id: "Australia/Currie", countrycode: "AU", country: "Australia", tz: "Australia/Currie", offset: "UTC +11:00" },
            "Australia/Darwin": { id: "Australia/Darwin", countrycode: "AU", country: "Australia", tz: "Australia/Darwin", offset: "UTC +09:30" },
            "Australia/Eucla": { id: "Australia/Eucla", countrycode: "AU", country: "Australia", tz: "Australia/Eucla", offset: "UTC +08:45" },
            "Australia/Hobart": { id: "Australia/Hobart", countrycode: "AU", country: "Australia", tz: "Australia/Hobart", offset: "UTC +11:00" },
            "Australia/Lindeman": { id: "Australia/Lindeman", countrycode: "AU", country: "Australia", tz: "Australia/Lindeman", offset: "UTC +10:00" },
            "Australia/Lord_Howe": { id: "Australia/Lord_Howe", countrycode: "AU", country: "Australia", tz: "Australia/Lord_Howe", offset: "UTC +11:00" },
            "Australia/Melbourne": { id: "Australia/Melbourne", countrycode: "AU", country: "Australia", tz: "Australia/Melbourne", offset: "UTC +11:00" },
            "Australia/Perth": { id: "Australia/Perth", countrycode: "AU", country: "Australia", tz: "Australia/Perth", offset: "UTC +08:00" },
            "Australia/Sydney": { id: "Australia/Sydney", countrycode: "AU", country: "Australia", tz: "Australia/Sydney", offset: "UTC +11:00" },
            "Europe/Vienna": { id: "Europe/Vienna", countrycode: "AT", country: "Austria", tz: "Europe/Vienna", offset: "UTC +01:00" },
            "Asia/Baku": { id: "Asia/Baku", countrycode: "AZ", country: "Azerbaijan", tz: "Asia/Baku", offset: "UTC +04:00" },
            "America/Nassau": { id: "America/Nassau", countrycode: "BS", country: "Bahamas", tz: "America/Nassau", offset: "UTC -05:00" },
            "Asia/Bahrain": { id: "Asia/Bahrain", countrycode: "BH", country: "Bahrain", tz: "Asia/Bahrain", offset: "UTC +03:00" },
            "Asia/Dhaka": { id: "Asia/Dhaka", countrycode: "BD", country: "Bangladesh", tz: "Asia/Dhaka", offset: "UTC +06:00" },
            "America/Barbados": { id: "America/Barbados", countrycode: "BB", country: "Barbados", tz: "America/Barbados", offset: "UTC -04:00" },
            "Europe/Minsk": { id: "Europe/Minsk", countrycode: "BY", country: "Belarus", tz: "Europe/Minsk", offset: "UTC +03:00" },
            "Europe/Brussels": { id: "Europe/Brussels", countrycode: "BE", country: "Belgium", tz: "Europe/Brussels", offset: "UTC +01:00" },
            "America/Belize": { id: "America/Belize", countrycode: "BZ", country: "Belize", tz: "America/Belize", offset: "UTC -06:00" },
            "Africa/Porto-Novo": { id: "Africa/Porto-Novo", countrycode: "BJ", country: "Benin", tz: "Africa/Porto-Novo", offset: "UTC +01:00" },
            "Atlantic/Bermuda": { id: "Atlantic/Bermuda", countrycode: "BM", country: "Bermuda", tz: "Atlantic/Bermuda", offset: "UTC -04:00" },
            "Asia/Thimphu": { id: "Asia/Thimphu", countrycode: "BT", country: "Bhutan", tz: "Asia/Thimphu", offset: "UTC +06:00" },
            "America/La_Paz": { id: "America/La_Paz", countrycode: "BO", country: "Bolivia, Plurinational State of", tz: "America/La_Paz", offset: "UTC -04:00" },
            "America/Kralendijk": { id: "America/Kralendijk", countrycode: "BQ", country: "Bonaire, Sint Eustatius and Saba", tz: "America/Kralendijk", offset: "UTC -04:00" },
            "Europe/Sarajevo": { id: "Europe/Sarajevo", countrycode: "BA", country: "Bosnia and Herzegovina", tz: "Europe/Sarajevo", offset: "UTC +01:00" },
            "Africa/Gaborone": { id: "Africa/Gaborone", countrycode: "BW", country: "Botswana", tz: "Africa/Gaborone", offset: "UTC +02:00" },
            "America/Araguaina": { id: "America/Araguaina", countrycode: "BR", country: "Brazil", tz: "America/Araguaina", offset: "UTC -03:00" },
            "America/Bahia": { id: "America/Bahia", countrycode: "BR", country: "Brazil", tz: "America/Bahia", offset: "UTC -03:00" },
            "America/Belem": { id: "America/Belem", countrycode: "BR", country: "Brazil", tz: "America/Belem", offset: "UTC -03:00" },
            "America/Boa_Vista": { id: "America/Boa_Vista", countrycode: "BR", country: "Brazil", tz: "America/Boa_Vista", offset: "UTC -04:00" },
            "America/Campo_Grande": { id: "America/Campo_Grande", countrycode: "BR", country: "Brazil", tz: "America/Campo_Grande", offset: "UTC -04:00" },
            "America/Cuiaba": { id: "America/Cuiaba", countrycode: "BR", country: "Brazil", tz: "America/Cuiaba", offset: "UTC -04:00" },
            "America/Eirunepe": { id: "America/Eirunepe", countrycode: "BR", country: "Brazil", tz: "America/Eirunepe", offset: "UTC -05:00" },
            "America/Fortaleza": { id: "America/Fortaleza", countrycode: "BR", country: "Brazil", tz: "America/Fortaleza", offset: "UTC -03:00" },
            "America/Maceio": { id: "America/Maceio", countrycode: "BR", country: "Brazil", tz: "America/Maceio", offset: "UTC -03:00" },
            "America/Manaus": { id: "America/Manaus", countrycode: "BR", country: "Brazil", tz: "America/Manaus", offset: "UTC -04:00" },
            "America/Noronha": { id: "America/Noronha", countrycode: "BR", country: "Brazil", tz: "America/Noronha", offset: "UTC -02:00" },
            "America/Porto_Velho": { id: "America/Porto_Velho", countrycode: "BR", country: "Brazil", tz: "America/Porto_Velho", offset: "UTC -04:00" },
            "America/Recife": { id: "America/Recife", countrycode: "BR", country: "Brazil", tz: "America/Recife", offset: "UTC -03:00" },
            "America/Rio_Branco": { id: "America/Rio_Branco", countrycode: "BR", country: "Brazil", tz: "America/Rio_Branco", offset: "UTC -05:00" },
            "America/Santarem": { id: "America/Santarem", countrycode: "BR", country: "Brazil", tz: "America/Santarem", offset: "UTC -03:00" },
            "America/Sao_Paulo": { id: "America/Sao_Paulo", countrycode: "BR", country: "Brazil", tz: "America/Sao_Paulo", offset: "UTC -03:00" },
            "Indian/Chagos": { id: "Indian/Chagos", countrycode: "IO", country: "British Indian Ocean Territory", tz: "Indian/Chagos", offset: "UTC +06:00" },
            "Asia/Brunei": { id: "Asia/Brunei", countrycode: "BN", country: "Brunei Darussalam", tz: "Asia/Brunei", offset: "UTC +08:00" },
            "Europe/Sofia": { id: "Europe/Sofia", countrycode: "BG", country: "Bulgaria", tz: "Europe/Sofia", offset: "UTC +02:00" },
            "Africa/Ouagadougou": { id: "Africa/Ouagadougou", countrycode: "BF", country: "Burkina Faso", tz: "Africa/Ouagadougou", offset: "UTC" },
            "Africa/Bujumbura": { id: "Africa/Bujumbura", countrycode: "BI", country: "Burundi", tz: "Africa/Bujumbura", offset: "UTC +02:00" },
            "Asia/Phnom_Penh": { id: "Asia/Phnom_Penh", countrycode: "KH", country: "Cambodia", tz: "Asia/Phnom_Penh", offset: "UTC +07:00" },
            "Africa/Douala": { id: "Africa/Douala", countrycode: "CM", country: "Cameroon", tz: "Africa/Douala", offset: "UTC +01:00" },
            "America/Atikokan": { id: "America/Atikokan", countrycode: "CA", country: "Canada", tz: "America/Atikokan", offset: "UTC -05:00" },
            "America/Blanc-Sablon": { id: "America/Blanc-Sablon", countrycode: "CA", country: "Canada", tz: "America/Blanc-Sablon", offset: "UTC -04:00" },
            "America/Cambridge_Bay": { id: "America/Cambridge_Bay", countrycode: "CA", country: "Canada", tz: "America/Cambridge_Bay", offset: "UTC -07:00" },
            "America/Creston": { id: "America/Creston", countrycode: "CA", country: "Canada", tz: "America/Creston", offset: "UTC -07:00" },
            "America/Dawson": { id: "America/Dawson", countrycode: "CA", country: "Canada", tz: "America/Dawson", offset: "UTC -08:00" },
            "America/Dawson_Creek": { id: "America/Dawson_Creek", countrycode: "CA", country: "Canada", tz: "America/Dawson_Creek", offset: "UTC -07:00" },
            "America/Edmonton": { id: "America/Edmonton", countrycode: "CA", country: "Canada", tz: "America/Edmonton", offset: "UTC -07:00" },
            "America/Fort_Nelson": { id: "America/Fort_Nelson", countrycode: "CA", country: "Canada", tz: "America/Fort_Nelson", offset: "UTC -07:00" },
            "America/Glace_Bay": { id: "America/Glace_Bay", countrycode: "CA", country: "Canada", tz: "America/Glace_Bay", offset: "UTC -04:00" },
            "America/Goose_Bay": { id: "America/Goose_Bay", countrycode: "CA", country: "Canada", tz: "America/Goose_Bay", offset: "UTC -04:00" },
            "America/Halifax": { id: "America/Halifax", countrycode: "CA", country: "Canada", tz: "America/Halifax", offset: "UTC -04:00" },
            "America/Inuvik": { id: "America/Inuvik", countrycode: "CA", country: "Canada", tz: "America/Inuvik", offset: "UTC -07:00" },
            "America/Iqaluit": { id: "America/Iqaluit", countrycode: "CA", country: "Canada", tz: "America/Iqaluit", offset: "UTC -05:00" },
            "America/Moncton": { id: "America/Moncton", countrycode: "CA", country: "Canada", tz: "America/Moncton", offset: "UTC -04:00" },
            "America/Nipigon": { id: "America/Nipigon", countrycode: "CA", country: "Canada", tz: "America/Nipigon", offset: "UTC -05:00" },
            "America/Pangnirtung": { id: "America/Pangnirtung", countrycode: "CA", country: "Canada", tz: "America/Pangnirtung", offset: "UTC -05:00" },
            "America/Rainy_River": { id: "America/Rainy_River", countrycode: "CA", country: "Canada", tz: "America/Rainy_River", offset: "UTC -06:00" },
            "America/Rankin_Inlet": { id: "America/Rankin_Inlet", countrycode: "CA", country: "Canada", tz: "America/Rankin_Inlet", offset: "UTC -06:00" },
            "America/Regina": { id: "America/Regina", countrycode: "CA", country: "Canada", tz: "America/Regina", offset: "UTC -06:00" },
            "America/Resolute": { id: "America/Resolute", countrycode: "CA", country: "Canada", tz: "America/Resolute", offset: "UTC -06:00" },
            "America/St_Johns": { id: "America/St_Johns", countrycode: "CA", country: "Canada", tz: "America/St_Johns", offset: "UTC -03:30" },
            "America/Swift_Current": { id: "America/Swift_Current", countrycode: "CA", country: "Canada", tz: "America/Swift_Current", offset: "UTC -06:00" },
            "America/Thunder_Bay": { id: "America/Thunder_Bay", countrycode: "CA", country: "Canada", tz: "America/Thunder_Bay", offset: "UTC -05:00" },
            "America/Toronto": { id: "America/Toronto", countrycode: "CA", country: "Canada", tz: "America/Toronto", offset: "UTC -05:00" },
            "America/Vancouver": { id: "America/Vancouver", countrycode: "CA", country: "Canada", tz: "America/Vancouver", offset: "UTC -08:00" },
            "America/Whitehorse": { id: "America/Whitehorse", countrycode: "CA", country: "Canada", tz: "America/Whitehorse", offset: "UTC -08:00" },
            "America/Winnipeg": { id: "America/Winnipeg", countrycode: "CA", country: "Canada", tz: "America/Winnipeg", offset: "UTC -06:00" },
            "America/Yellowknife": { id: "America/Yellowknife", countrycode: "CA", country: "Canada", tz: "America/Yellowknife", offset: "UTC -07:00" },
            "Atlantic/Cape_Verde": { id: "Atlantic/Cape_Verde", countrycode: "CV", country: "Cape Verde", tz: "Atlantic/Cape_Verde", offset: "UTC -01:00" },
            "America/Cayman": { id: "America/Cayman", countrycode: "KY", country: "Cayman Islands", tz: "America/Cayman", offset: "UTC -05:00" },
            "Africa/Bangui": { id: "Africa/Bangui", countrycode: "CF", country: "Central African Republic", tz: "Africa/Bangui", offset: "UTC +01:00" },
            "Africa/Ndjamena": { id: "Africa/Ndjamena", countrycode: "TD", country: "Chad", tz: "Africa/Ndjamena", offset: "UTC +01:00" },
            "America/Punta_Arenas": { id: "America/Punta_Arenas", countrycode: "CL", country: "Chile", tz: "America/Punta_Arenas", offset: "UTC -03:00" },
            "America/Santiago": { id: "America/Santiago", countrycode: "CL", country: "Chile", tz: "America/Santiago", offset: "UTC -03:00" },
            "Pacific/Easter": { id: "Pacific/Easter", countrycode: "CL", country: "Chile", tz: "Pacific/Easter", offset: "UTC -05:00" },
            "Asia/Shanghai": { id: "Asia/Shanghai", countrycode: "CN", country: "China", tz: "Asia/Shanghai", offset: "UTC +08:00" },
            "Asia/Urumqi": { id: "Asia/Urumqi", countrycode: "CN", country: "China", tz: "Asia/Urumqi", offset: "UTC +06:00" },
            "Indian/Christmas": { id: "Indian/Christmas", countrycode: "CX", country: "Christmas Island", tz: "Indian/Christmas", offset: "UTC +07:00" },
            "Indian/Cocos": { id: "Indian/Cocos", countrycode: "CC", country: "Cocos (Keeling) Islands", tz: "Indian/Cocos", offset: "UTC +06:30" },
            "America/Bogota": { id: "America/Bogota", countrycode: "CO", country: "Colombia", tz: "America/Bogota", offset: "UTC -05:00" },
            "Indian/Comoro": { id: "Indian/Comoro", countrycode: "KM", country: "Comoros", tz: "Indian/Comoro", offset: "UTC +03:00" },
            "Africa/Brazzaville": { id: "Africa/Brazzaville", countrycode: "CG", country: "Congo", tz: "Africa/Brazzaville", offset: "UTC +01:00" },
            "Africa/Kinshasa": { id: "Africa/Kinshasa", countrycode: "CD", country: "Congo, the Democratic Republic of the", tz: "Africa/Kinshasa", offset: "UTC +01:00" },
            "Africa/Lubumbashi": { id: "Africa/Lubumbashi", countrycode: "CD", country: "Congo, the Democratic Republic of the", tz: "Africa/Lubumbashi", offset: "UTC +02:00" },
            "Pacific/Rarotonga": { id: "Pacific/Rarotonga", countrycode: "CK", country: "Cook Islands", tz: "Pacific/Rarotonga", offset: "UTC -10:00" },
            "America/Costa_Rica": { id: "America/Costa_Rica", countrycode: "CR", country: "Costa Rica", tz: "America/Costa_Rica", offset: "UTC -06:00" },
            "Europe/Zagreb": { id: "Europe/Zagreb", countrycode: "HR", country: "Croatia", tz: "Europe/Zagreb", offset: "UTC +01:00" },
            "America/Havana": { id: "America/Havana", countrycode: "CU", country: "Cuba", tz: "America/Havana", offset: "UTC -05:00" },
            "America/Curacao": { id: "America/Curacao", countrycode: "CW", country: "Curaçao", tz: "America/Curacao", offset: "UTC -04:00" },
            "Asia/Famagusta": { id: "Asia/Famagusta", countrycode: "CY", country: "Cyprus", tz: "Asia/Famagusta", offset: "UTC +02:00" },
            "Asia/Nicosia": { id: "Asia/Nicosia", countrycode: "CY", country: "Cyprus", tz: "Asia/Nicosia", offset: "UTC +02:00" },
            "Europe/Prague": { id: "Europe/Prague", countrycode: "CZ", country: "Czech Republic", tz: "Europe/Prague", offset: "UTC +01:00" },
            "Africa/Abidjan": { id: "Africa/Abidjan", countrycode: "CI", country: "Côte d'Ivoire", tz: "Africa/Abidjan", offset: "UTC" },
            "Europe/Copenhagen": { id: "Europe/Copenhagen", countrycode: "DK", country: "Denmark", tz: "Europe/Copenhagen", offset: "UTC +01:00" },
            "Africa/Djibouti": { id: "Africa/Djibouti", countrycode: "DJ", country: "Djibouti", tz: "Africa/Djibouti", offset: "UTC +03:00" },
            "America/Dominica": { id: "America/Dominica", countrycode: "DM", country: "Dominica", tz: "America/Dominica", offset: "UTC -04:00" },
            "America/Santo_Domingo": { id: "America/Santo_Domingo", countrycode: "DO", country: "Dominican Republic", tz: "America/Santo_Domingo", offset: "UTC -04:00" },
            "America/Guayaquil": { id: "America/Guayaquil", countrycode: "EC", country: "Ecuador", tz: "America/Guayaquil", offset: "UTC -05:00" },
            "Pacific/Galapagos": { id: "Pacific/Galapagos", countrycode: "EC", country: "Ecuador", tz: "Pacific/Galapagos", offset: "UTC -06:00" },
            "Africa/Cairo": { id: "Africa/Cairo", countrycode: "EG", country: "Egypt", tz: "Africa/Cairo", offset: "UTC +02:00" },
            "America/El_Salvador": { id: "America/El_Salvador", countrycode: "SV", country: "El Salvador", tz: "America/El_Salvador", offset: "UTC -06:00" },
            "Africa/Malabo": { id: "Africa/Malabo", countrycode: "GQ", country: "Equatorial Guinea", tz: "Africa/Malabo", offset: "UTC +01:00" },
            "Africa/Asmara": { id: "Africa/Asmara", countrycode: "ER", country: "Eritrea", tz: "Africa/Asmara", offset: "UTC +03:00" },
            "Europe/Tallinn": { id: "Europe/Tallinn", countrycode: "EE", country: "Estonia", tz: "Europe/Tallinn", offset: "UTC +02:00" },
            "Africa/Addis_Ababa": { id: "Africa/Addis_Ababa", countrycode: "ET", country: "Ethiopia", tz: "Africa/Addis_Ababa", offset: "UTC +03:00" },
            "Atlantic/Stanley": { id: "Atlantic/Stanley", countrycode: "FK", country: "Falkland Islands (Malvinas)", tz: "Atlantic/Stanley", offset: "UTC -03:00" },
            "Atlantic/Faroe": { id: "Atlantic/Faroe", countrycode: "FO", country: "Faroe Islands", tz: "Atlantic/Faroe", offset: "UTC" },
            "Pacific/Fiji": { id: "Pacific/Fiji", countrycode: "FJ", country: "Fiji", tz: "Pacific/Fiji", offset: "UTC +12:00" },
            "Europe/Helsinki": { id: "Europe/Helsinki", countrycode: "FI", country: "Finland", tz: "Europe/Helsinki", offset: "UTC +02:00" },
            "Europe/Paris": { id: "Europe/Paris", countrycode: "FR", country: "France", tz: "Europe/Paris", offset: "UTC +01:00" },
            "America/Cayenne": { id: "America/Cayenne", countrycode: "GF", country: "French Guiana", tz: "America/Cayenne", offset: "UTC -03:00" },
            "Pacific/Gambier": { id: "Pacific/Gambier", countrycode: "PF", country: "French Polynesia", tz: "Pacific/Gambier", offset: "UTC -09:00" },
            "Pacific/Marquesas": { id: "Pacific/Marquesas", countrycode: "PF", country: "French Polynesia", tz: "Pacific/Marquesas", offset: "UTC -09:30" },
            "Pacific/Tahiti": { id: "Pacific/Tahiti", countrycode: "PF", country: "French Polynesia", tz: "Pacific/Tahiti", offset: "UTC -10:00" },
            "Indian/Kerguelen": { id: "Indian/Kerguelen", countrycode: "TF", country: "French Southern Territories", tz: "Indian/Kerguelen", offset: "UTC +05:00" },
            "Africa/Libreville": { id: "Africa/Libreville", countrycode: "GA", country: "Gabon", tz: "Africa/Libreville", offset: "UTC +01:00" },
            "Africa/Banjul": { id: "Africa/Banjul", countrycode: "GM", country: "Gambia", tz: "Africa/Banjul", offset: "UTC" },
            "Asia/Tbilisi": { id: "Asia/Tbilisi", countrycode: "GE", country: "Georgia", tz: "Asia/Tbilisi", offset: "UTC +04:00" },
            "Europe/Berlin": { id: "Europe/Berlin", countrycode: "DE", country: "Germany", tz: "Europe/Berlin", offset: "UTC +01:00" },
            "Europe/Busingen": { id: "Europe/Busingen", countrycode: "DE", country: "Germany", tz: "Europe/Busingen", offset: "UTC +01:00" },
            "Africa/Accra": { id: "Africa/Accra", countrycode: "GH", country: "Ghana", tz: "Africa/Accra", offset: "UTC" },
            "Europe/Gibraltar": { id: "Europe/Gibraltar", countrycode: "GI", country: "Gibraltar", tz: "Europe/Gibraltar", offset: "UTC +01:00" },
            "Europe/Athens": { id: "Europe/Athens", countrycode: "GR", country: "Greece", tz: "Europe/Athens", offset: "UTC +02:00" },
            "America/Danmarkshavn": { id: "America/Danmarkshavn", countrycode: "GL", country: "Greenland", tz: "America/Danmarkshavn", offset: "UTC" },
            "America/Godthab": { id: "America/Godthab", countrycode: "GL", country: "Greenland", tz: "America/Godthab", offset: "UTC -03:00" },
            "America/Scoresbysund": { id: "America/Scoresbysund", countrycode: "GL", country: "Greenland", tz: "America/Scoresbysund", offset: "UTC -01:00" },
            "America/Thule": { id: "America/Thule", countrycode: "GL", country: "Greenland", tz: "America/Thule", offset: "UTC -04:00" },
            "America/Grenada": { id: "America/Grenada", countrycode: "GD", country: "Grenada", tz: "America/Grenada", offset: "UTC -04:00" },
            "America/Guadeloupe": { id: "America/Guadeloupe", countrycode: "GP", country: "Guadeloupe", tz: "America/Guadeloupe", offset: "UTC -04:00" },
            "Pacific/Guam": { id: "Pacific/Guam", countrycode: "GU", country: "Guam", tz: "Pacific/Guam", offset: "UTC +10:00" },
            "America/Guatemala": { id: "America/Guatemala", countrycode: "GT", country: "Guatemala", tz: "America/Guatemala", offset: "UTC -06:00" },
            "Europe/Guernsey": { id: "Europe/Guernsey", countrycode: "GG", country: "Guernsey", tz: "Europe/Guernsey", offset: "UTC" },
            "Africa/Conakry": { id: "Africa/Conakry", countrycode: "GN", country: "Guinea", tz: "Africa/Conakry", offset: "UTC" },
            "Africa/Bissau": { id: "Africa/Bissau", countrycode: "GW", country: "Guinea-Bissau", tz: "Africa/Bissau", offset: "UTC" },
            "America/Guyana": { id: "America/Guyana", countrycode: "GY", country: "Guyana", tz: "America/Guyana", offset: "UTC -04:00" },
            "America/Port-au-Prince": { id: "America/Port-au-Prince", countrycode: "HT", country: "Haiti", tz: "America/Port-au-Prince", offset: "UTC -05:00" },
            "Europe/Vatican": { id: "Europe/Vatican", countrycode: "VA", country: "Holy See (Vatican City State)", tz: "Europe/Vatican", offset: "UTC +01:00" },
            "America/Tegucigalpa": { id: "America/Tegucigalpa", countrycode: "HN", country: "Honduras", tz: "America/Tegucigalpa", offset: "UTC -06:00" },
            "Asia/Hong_Kong": { id: "Asia/Hong_Kong", countrycode: "HK", country: "Hong Kong", tz: "Asia/Hong_Kong", offset: "UTC +08:00" },
            "Europe/Budapest": { id: "Europe/Budapest", countrycode: "HU", country: "Hungary", tz: "Europe/Budapest", offset: "UTC +01:00" },
            "Atlantic/Reykjavik": { id: "Atlantic/Reykjavik", countrycode: "IS", country: "Iceland", tz: "Atlantic/Reykjavik", offset: "UTC" },
            "Asia/Kolkata": { id: "Asia/Kolkata", countrycode: "IN", country: "India", tz: "Asia/Kolkata", offset: "UTC +05:30" },
            "Asia/Jakarta": { id: "Asia/Jakarta", countrycode: "ID", country: "Indonesia", tz: "Asia/Jakarta", offset: "UTC +07:00" },
            "Asia/Jayapura": { id: "Asia/Jayapura", countrycode: "ID", country: "Indonesia", tz: "Asia/Jayapura", offset: "UTC +09:00" },
            "Asia/Makassar": { id: "Asia/Makassar", countrycode: "ID", country: "Indonesia", tz: "Asia/Makassar", offset: "UTC +08:00" },
            "Asia/Pontianak": { id: "Asia/Pontianak", countrycode: "ID", country: "Indonesia", tz: "Asia/Pontianak", offset: "UTC +07:00" },
            "Asia/Tehran": { id: "Asia/Tehran", countrycode: "IR", country: "Iran, Islamic Republic of", tz: "Asia/Tehran", offset: "UTC +03:30" },
            "Asia/Baghdad": { id: "Asia/Baghdad", countrycode: "IQ", country: "Iraq", tz: "Asia/Baghdad", offset: "UTC +03:00" },
            "Europe/Dublin": { id: "Europe/Dublin", countrycode: "IE", country: "Ireland", tz: "Europe/Dublin", offset: "UTC" },
            "Europe/Isle_of_Man": { id: "Europe/Isle_of_Man", countrycode: "IM", country: "Isle of Man", tz: "Europe/Isle_of_Man", offset: "UTC" },
            "Asia/Jerusalem": { id: "Asia/Jerusalem", countrycode: "IL", country: "Israel", tz: "Asia/Jerusalem", offset: "UTC +02:00" },
            "Europe/Rome": { id: "Europe/Rome", countrycode: "IT", country: "Italy", tz: "Europe/Rome", offset: "UTC +01:00" },
            "America/Jamaica": { id: "America/Jamaica", countrycode: "JM", country: "Jamaica", tz: "America/Jamaica", offset: "UTC -05:00" },
            "Asia/Tokyo": { id: "Asia/Tokyo", countrycode: "JP", country: "Japan", tz: "Asia/Tokyo", offset: "UTC +09:00" },
            "Europe/Jersey": { id: "Europe/Jersey", countrycode: "JE", country: "Jersey", tz: "Europe/Jersey", offset: "UTC" },
            "Asia/Amman": { id: "Asia/Amman", countrycode: "JO", country: "Jordan", tz: "Asia/Amman", offset: "UTC +02:00" },
            "Asia/Almaty": { id: "Asia/Almaty", countrycode: "KZ", country: "Kazakhstan", tz: "Asia/Almaty", offset: "UTC +06:00" },
            "Asia/Aqtau": { id: "Asia/Aqtau", countrycode: "KZ", country: "Kazakhstan", tz: "Asia/Aqtau", offset: "UTC +05:00" },
            "Asia/Aqtobe": { id: "Asia/Aqtobe", countrycode: "KZ", country: "Kazakhstan", tz: "Asia/Aqtobe", offset: "UTC +05:00" },
            "Asia/Atyrau": { id: "Asia/Atyrau", countrycode: "KZ", country: "Kazakhstan", tz: "Asia/Atyrau", offset: "UTC +05:00" },
            "Asia/Oral": { id: "Asia/Oral", countrycode: "KZ", country: "Kazakhstan", tz: "Asia/Oral", offset: "UTC +05:00" },
            "Asia/Qostanay": { id: "Asia/Qostanay", countrycode: "KZ", country: "Kazakhstan", tz: "Asia/Qostanay", offset: "UTC +06:00" },
            "Asia/Qyzylorda": { id: "Asia/Qyzylorda", countrycode: "KZ", country: "Kazakhstan", tz: "Asia/Qyzylorda", offset: "UTC +05:00" },
            "Africa/Nairobi": { id: "Africa/Nairobi", countrycode: "KE", country: "Kenya", tz: "Africa/Nairobi", offset: "UTC +03:00" },
            "Pacific/Enderbury": { id: "Pacific/Enderbury", countrycode: "KI", country: "Kiribati", tz: "Pacific/Enderbury", offset: "UTC +13:00" },
            "Pacific/Kiritimati": { id: "Pacific/Kiritimati", countrycode: "KI", country: "Kiribati", tz: "Pacific/Kiritimati", offset: "UTC +14:00" },
            "Pacific/Tarawa": { id: "Pacific/Tarawa", countrycode: "KI", country: "Kiribati", tz: "Pacific/Tarawa", offset: "UTC +12:00" },
            "Asia/Pyongyang": { id: "Asia/Pyongyang", countrycode: "KP", country: "Korea, Democratic People's Republic of", tz: "Asia/Pyongyang", offset: "UTC +09:00" },
            "Asia/Seoul": { id: "Asia/Seoul", countrycode: "KR", country: "Korea, Republic of", tz: "Asia/Seoul", offset: "UTC +09:00" },
            "Asia/Kuwait": { id: "Asia/Kuwait", countrycode: "KW", country: "Kuwait", tz: "Asia/Kuwait", offset: "UTC +03:00" },
            "Asia/Bishkek": { id: "Asia/Bishkek", countrycode: "KG", country: "Kyrgyzstan", tz: "Asia/Bishkek", offset: "UTC +06:00" },
            "Asia/Vientiane": { id: "Asia/Vientiane", countrycode: "LA", country: "Lao People's Democratic Republic", tz: "Asia/Vientiane", offset: "UTC +07:00" },
            "Europe/Riga": { id: "Europe/Riga", countrycode: "LV", country: "Latvia", tz: "Europe/Riga", offset: "UTC +02:00" },
            "Asia/Beirut": { id: "Asia/Beirut", countrycode: "LB", country: "Lebanon", tz: "Asia/Beirut", offset: "UTC +02:00" },
            "Africa/Maseru": { id: "Africa/Maseru", countrycode: "LS", country: "Lesotho", tz: "Africa/Maseru", offset: "UTC +02:00" },
            "Africa/Monrovia": { id: "Africa/Monrovia", countrycode: "LR", country: "Liberia", tz: "Africa/Monrovia", offset: "UTC" },
            "Africa/Tripoli": { id: "Africa/Tripoli", countrycode: "LY", country: "Libya", tz: "Africa/Tripoli", offset: "UTC +02:00" },
            "Europe/Vaduz": { id: "Europe/Vaduz", countrycode: "LI", country: "Liechtenstein", tz: "Europe/Vaduz", offset: "UTC +01:00" },
            "Europe/Vilnius": { id: "Europe/Vilnius", countrycode: "LT", country: "Lithuania", tz: "Europe/Vilnius", offset: "UTC +02:00" },
            "Europe/Luxembourg": { id: "Europe/Luxembourg", countrycode: "LU", country: "Luxembourg", tz: "Europe/Luxembourg", offset: "UTC +01:00" },
            "Asia/Macau": { id: "Asia/Macau", countrycode: "MO", country: "Macao", tz: "Asia/Macau", offset: "UTC +08:00" },
            "Europe/Skopje": { id: "Europe/Skopje", countrycode: "MK", country: "Macedonia, the Former Yugoslav Republic of", tz: "Europe/Skopje", offset: "UTC +01:00" },
            "Indian/Antananarivo": { id: "Indian/Antananarivo", countrycode: "MG", country: "Madagascar", tz: "Indian/Antananarivo", offset: "UTC +03:00" },
            "Africa/Blantyre": { id: "Africa/Blantyre", countrycode: "MW", country: "Malawi", tz: "Africa/Blantyre", offset: "UTC +02:00" },
            "Asia/Kuala_Lumpur": { id: "Asia/Kuala_Lumpur", countrycode: "MY", country: "Malaysia", tz: "Asia/Kuala_Lumpur", offset: "UTC +08:00" },
            "Asia/Kuching": { id: "Asia/Kuching", countrycode: "MY", country: "Malaysia", tz: "Asia/Kuching", offset: "UTC +08:00" },
            "Indian/Maldives": { id: "Indian/Maldives", countrycode: "MV", country: "Maldives", tz: "Indian/Maldives", offset: "UTC +05:00" },
            "Africa/Bamako": { id: "Africa/Bamako", countrycode: "ML", country: "Mali", tz: "Africa/Bamako", offset: "UTC" },
            "Europe/Malta": { id: "Europe/Malta", countrycode: "MT", country: "Malta", tz: "Europe/Malta", offset: "UTC +01:00" },
            "Pacific/Kwajalein": { id: "Pacific/Kwajalein", countrycode: "MH", country: "Marshall Islands", tz: "Pacific/Kwajalein", offset: "UTC +12:00" },
            "Pacific/Majuro": { id: "Pacific/Majuro", countrycode: "MH", country: "Marshall Islands", tz: "Pacific/Majuro", offset: "UTC +12:00" },
            "America/Martinique": { id: "America/Martinique", countrycode: "MQ", country: "Martinique", tz: "America/Martinique", offset: "UTC -04:00" },
            "Africa/Nouakchott": { id: "Africa/Nouakchott", countrycode: "MR", country: "Mauritania", tz: "Africa/Nouakchott", offset: "UTC" },
            "Indian/Mauritius": { id: "Indian/Mauritius", countrycode: "MU", country: "Mauritius", tz: "Indian/Mauritius", offset: "UTC +04:00" },
            "Indian/Mayotte": { id: "Indian/Mayotte", countrycode: "YT", country: "Mayotte", tz: "Indian/Mayotte", offset: "UTC +03:00" },
            "America/Bahia_Banderas": { id: "America/Bahia_Banderas", countrycode: "MX", country: "Mexico", tz: "America/Bahia_Banderas", offset: "UTC -06:00" },
            "America/Cancun": { id: "America/Cancun", countrycode: "MX", country: "Mexico", tz: "America/Cancun", offset: "UTC -05:00" },
            "America/Chihuahua": { id: "America/Chihuahua", countrycode: "MX", country: "Mexico", tz: "America/Chihuahua", offset: "UTC -07:00" },
            "America/Hermosillo": { id: "America/Hermosillo", countrycode: "MX", country: "Mexico", tz: "America/Hermosillo", offset: "UTC -07:00" },
            "America/Matamoros": { id: "America/Matamoros", countrycode: "MX", country: "Mexico", tz: "America/Matamoros", offset: "UTC -06:00" },
            "America/Mazatlan": { id: "America/Mazatlan", countrycode: "MX", country: "Mexico", tz: "America/Mazatlan", offset: "UTC -07:00" },
            "America/Merida": { id: "America/Merida", countrycode: "MX", country: "Mexico", tz: "America/Merida", offset: "UTC -06:00" },
            "America/Mexico_City": { id: "America/Mexico_City", countrycode: "MX", country: "Mexico", tz: "America/Mexico_City", offset: "UTC -06:00" },
            "America/Monterrey": { id: "America/Monterrey", countrycode: "MX", country: "Mexico", tz: "America/Monterrey", offset: "UTC -06:00" },
            "America/Ojinaga": { id: "America/Ojinaga", countrycode: "MX", country: "Mexico", tz: "America/Ojinaga", offset: "UTC -07:00" },
            "America/Tijuana": { id: "America/Tijuana", countrycode: "MX", country: "Mexico", tz: "America/Tijuana", offset: "UTC -08:00" },
            "Pacific/Chuuk": { id: "Pacific/Chuuk", countrycode: "FM", country: "Micronesia, Federated States of", tz: "Pacific/Chuuk", offset: "UTC +10:00" },
            "Pacific/Kosrae": { id: "Pacific/Kosrae", countrycode: "FM", country: "Micronesia, Federated States of", tz: "Pacific/Kosrae", offset: "UTC +11:00" },
            "Pacific/Pohnpei": { id: "Pacific/Pohnpei", countrycode: "FM", country: "Micronesia, Federated States of", tz: "Pacific/Pohnpei", offset: "UTC +11:00" },
            "Europe/Chisinau": { id: "Europe/Chisinau", countrycode: "MD", country: "Moldova, Republic of", tz: "Europe/Chisinau", offset: "UTC +02:00" },
            "Europe/Monaco": { id: "Europe/Monaco", countrycode: "MC", country: "Monaco", tz: "Europe/Monaco", offset: "UTC +01:00" },
            "Asia/Choibalsan": { id: "Asia/Choibalsan", countrycode: "MN", country: "Mongolia", tz: "Asia/Choibalsan", offset: "UTC +08:00" },
            "Asia/Hovd": { id: "Asia/Hovd", countrycode: "MN", country: "Mongolia", tz: "Asia/Hovd", offset: "UTC +07:00" },
            "Asia/Ulaanbaatar": { id: "Asia/Ulaanbaatar", countrycode: "MN", country: "Mongolia", tz: "Asia/Ulaanbaatar", offset: "UTC +08:00" },
            "Europe/Podgorica": { id: "Europe/Podgorica", countrycode: "ME", country: "Montenegro", tz: "Europe/Podgorica", offset: "UTC +01:00" },
            "America/Montserrat": { id: "America/Montserrat", countrycode: "MS", country: "Montserrat", tz: "America/Montserrat", offset: "UTC -04:00" },
            "Africa/Casablanca": { id: "Africa/Casablanca", countrycode: "MA", country: "Morocco", tz: "Africa/Casablanca", offset: "UTC +01:00" },
            "Africa/Maputo": { id: "Africa/Maputo", countrycode: "MZ", country: "Mozambique", tz: "Africa/Maputo", offset: "UTC +02:00" },
            "Asia/Yangon": { id: "Asia/Yangon", countrycode: "MM", country: "Myanmar", tz: "Asia/Yangon", offset: "UTC +06:30" },
            "Africa/Windhoek": { id: "Africa/Windhoek", countrycode: "NA", country: "Namibia", tz: "Africa/Windhoek", offset: "UTC +02:00" },
            "Pacific/Nauru": { id: "Pacific/Nauru", countrycode: "NR", country: "Nauru", tz: "Pacific/Nauru", offset: "UTC +12:00" },
            "Asia/Kathmandu": { id: "Asia/Kathmandu", countrycode: "NP", country: "Nepal", tz: "Asia/Kathmandu", offset: "UTC +05:45" },
            "Europe/Amsterdam": { id: "Europe/Amsterdam", countrycode: "NL", country: "Netherlands", tz: "Europe/Amsterdam", offset: "UTC +01:00" },
            "Pacific/Noumea": { id: "Pacific/Noumea", countrycode: "NC", country: "New Caledonia", tz: "Pacific/Noumea", offset: "UTC +11:00" },
            "Pacific/Auckland": { id: "Pacific/Auckland", countrycode: "NZ", country: "New Zealand", tz: "Pacific/Auckland", offset: "UTC +13:00" },
            "Pacific/Chatham": { id: "Pacific/Chatham", countrycode: "NZ", country: "New Zealand", tz: "Pacific/Chatham", offset: "UTC +13:45" },
            "America/Managua": { id: "America/Managua", countrycode: "NI", country: "Nicaragua", tz: "America/Managua", offset: "UTC -06:00" },
            "Africa/Niamey": { id: "Africa/Niamey", countrycode: "NE", country: "Niger", tz: "Africa/Niamey", offset: "UTC +01:00" },
            "Africa/Lagos": { id: "Africa/Lagos", countrycode: "NG", country: "Nigeria", tz: "Africa/Lagos", offset: "UTC +01:00" },
            "Pacific/Niue": { id: "Pacific/Niue", countrycode: "NU", country: "Niue", tz: "Pacific/Niue", offset: "UTC -11:00" },
            "Pacific/Norfolk": { id: "Pacific/Norfolk", countrycode: "NF", country: "Norfolk Island", tz: "Pacific/Norfolk", offset: "UTC +12:00" },
            "Pacific/Saipan": { id: "Pacific/Saipan", countrycode: "MP", country: "Northern Mariana Islands", tz: "Pacific/Saipan", offset: "UTC +10:00" },
            "Europe/Oslo": { id: "Europe/Oslo", countrycode: "NO", country: "Norway", tz: "Europe/Oslo", offset: "UTC +01:00" },
            "Asia/Muscat": { id: "Asia/Muscat", countrycode: "OM", country: "Oman", tz: "Asia/Muscat", offset: "UTC +04:00" },
            "Asia/Karachi": { id: "Asia/Karachi", countrycode: "PK", country: "Pakistan", tz: "Asia/Karachi", offset: "UTC +05:00" },
            "Pacific/Palau": { id: "Pacific/Palau", countrycode: "PW", country: "Palau", tz: "Pacific/Palau", offset: "UTC +09:00" },
            "Asia/Gaza": { id: "Asia/Gaza", countrycode: "PS", country: "Palestine, State of", tz: "Asia/Gaza", offset: "UTC +02:00" },
            "Asia/Hebron": { id: "Asia/Hebron", countrycode: "PS", country: "Palestine, State of", tz: "Asia/Hebron", offset: "UTC +02:00" },
            "America/Panama": { id: "America/Panama", countrycode: "PA", country: "Panama", tz: "America/Panama", offset: "UTC -05:00" },
            "Pacific/Bougainville": { id: "Pacific/Bougainville", countrycode: "PG", country: "Papua New Guinea", tz: "Pacific/Bougainville", offset: "UTC +11:00" },
            "Pacific/Port_Moresby": { id: "Pacific/Port_Moresby", countrycode: "PG", country: "Papua New Guinea", tz: "Pacific/Port_Moresby", offset: "UTC +10:00" },
            "America/Asuncion": { id: "America/Asuncion", countrycode: "PY", country: "Paraguay", tz: "America/Asuncion", offset: "UTC -03:00" },
            "America/Lima": { id: "America/Lima", countrycode: "PE", country: "Peru", tz: "America/Lima", offset: "UTC -05:00" },
            "Asia/Manila": { id: "Asia/Manila", countrycode: "PH", country: "Philippines", tz: "Asia/Manila", offset: "UTC +08:00" },
            "Pacific/Pitcairn": { id: "Pacific/Pitcairn", countrycode: "PN", country: "Pitcairn", tz: "Pacific/Pitcairn", offset: "UTC -08:00" },
            "Europe/Warsaw": { id: "Europe/Warsaw", countrycode: "PL", country: "Poland", tz: "Europe/Warsaw", offset: "UTC +01:00" },
            "Atlantic/Azores": { id: "Atlantic/Azores", countrycode: "PT", country: "Portugal", tz: "Atlantic/Azores", offset: "UTC -01:00" },
            "Atlantic/Madeira": { id: "Atlantic/Madeira", countrycode: "PT", country: "Portugal", tz: "Atlantic/Madeira", offset: "UTC" },
            "Europe/Lisbon": { id: "Europe/Lisbon", countrycode: "PT", country: "Portugal", tz: "Europe/Lisbon", offset: "UTC" },
            "America/Puerto_Rico": { id: "America/Puerto_Rico", countrycode: "PR", country: "Puerto Rico", tz: "America/Puerto_Rico", offset: "UTC -04:00" },
            "Asia/Qatar": { id: "Asia/Qatar", countrycode: "QA", country: "Qatar", tz: "Asia/Qatar", offset: "UTC +03:00" },
            "Europe/Bucharest": { id: "Europe/Bucharest", countrycode: "RO", country: "Romania", tz: "Europe/Bucharest", offset: "UTC +02:00" },
            "Asia/Anadyr": { id: "Asia/Anadyr", countrycode: "RU", country: "Russian Federation", tz: "Asia/Anadyr", offset: "UTC +12:00" },
            "Asia/Barnaul": { id: "Asia/Barnaul", countrycode: "RU", country: "Russian Federation", tz: "Asia/Barnaul", offset: "UTC +07:00" },
            "Asia/Chita": { id: "Asia/Chita", countrycode: "RU", country: "Russian Federation", tz: "Asia/Chita", offset: "UTC +09:00" },
            "Asia/Irkutsk": { id: "Asia/Irkutsk", countrycode: "RU", country: "Russian Federation", tz: "Asia/Irkutsk", offset: "UTC +08:00" },
            "Asia/Kamchatka": { id: "Asia/Kamchatka", countrycode: "RU", country: "Russian Federation", tz: "Asia/Kamchatka", offset: "UTC +12:00" },
            "Asia/Khandyga": { id: "Asia/Khandyga", countrycode: "RU", country: "Russian Federation", tz: "Asia/Khandyga", offset: "UTC +09:00" },
            "Asia/Krasnoyarsk": { id: "Asia/Krasnoyarsk", countrycode: "RU", country: "Russian Federation", tz: "Asia/Krasnoyarsk", offset: "UTC +07:00" },
            "Asia/Magadan": { id: "Asia/Magadan", countrycode: "RU", country: "Russian Federation", tz: "Asia/Magadan", offset: "UTC +11:00" },
            "Asia/Novokuznetsk": { id: "Asia/Novokuznetsk", countrycode: "RU", country: "Russian Federation", tz: "Asia/Novokuznetsk", offset: "UTC +07:00" },
            "Asia/Novosibirsk": { id: "Asia/Novosibirsk", countrycode: "RU", country: "Russian Federation", tz: "Asia/Novosibirsk", offset: "UTC +07:00" },
            "Asia/Omsk": { id: "Asia/Omsk", countrycode: "RU", country: "Russian Federation", tz: "Asia/Omsk", offset: "UTC +06:00" },
            "Asia/Sakhalin": { id: "Asia/Sakhalin", countrycode: "RU", country: "Russian Federation", tz: "Asia/Sakhalin", offset: "UTC +11:00" },
            "Asia/Srednekolymsk": { id: "Asia/Srednekolymsk", countrycode: "RU", country: "Russian Federation", tz: "Asia/Srednekolymsk", offset: "UTC +11:00" },
            "Asia/Tomsk": { id: "Asia/Tomsk", countrycode: "RU", country: "Russian Federation", tz: "Asia/Tomsk", offset: "UTC +07:00" },
            "Asia/Ust-Nera": { id: "Asia/Ust-Nera", countrycode: "RU", country: "Russian Federation", tz: "Asia/Ust-Nera", offset: "UTC +10:00" },
            "Asia/Vladivostok": { id: "Asia/Vladivostok", countrycode: "RU", country: "Russian Federation", tz: "Asia/Vladivostok", offset: "UTC +10:00" },
            "Asia/Yakutsk": { id: "Asia/Yakutsk", countrycode: "RU", country: "Russian Federation", tz: "Asia/Yakutsk", offset: "UTC +09:00" },
            "Asia/Yekaterinburg": { id: "Asia/Yekaterinburg", countrycode: "RU", country: "Russian Federation", tz: "Asia/Yekaterinburg", offset: "UTC +05:00" },
            "Europe/Astrakhan": { id: "Europe/Astrakhan", countrycode: "RU", country: "Russian Federation", tz: "Europe/Astrakhan", offset: "UTC +04:00" },
            "Europe/Kaliningrad": { id: "Europe/Kaliningrad", countrycode: "RU", country: "Russian Federation", tz: "Europe/Kaliningrad", offset: "UTC +02:00" },
            "Europe/Kirov": { id: "Europe/Kirov", countrycode: "RU", country: "Russian Federation", tz: "Europe/Kirov", offset: "UTC +03:00" },
            "Europe/Moscow": { id: "Europe/Moscow", countrycode: "RU", country: "Russian Federation", tz: "Europe/Moscow", offset: "UTC +03:00" },
            "Europe/Samara": { id: "Europe/Samara", countrycode: "RU", country: "Russian Federation", tz: "Europe/Samara", offset: "UTC +04:00" },
            "Europe/Saratov": { id: "Europe/Saratov", countrycode: "RU", country: "Russian Federation", tz: "Europe/Saratov", offset: "UTC +04:00" },
            "Europe/Ulyanovsk": { id: "Europe/Ulyanovsk", countrycode: "RU", country: "Russian Federation", tz: "Europe/Ulyanovsk", offset: "UTC +04:00" },
            "Europe/Volgograd": { id: "Europe/Volgograd", countrycode: "RU", country: "Russian Federation", tz: "Europe/Volgograd", offset: "UTC +04:00" },
            "Africa/Kigali": { id: "Africa/Kigali", countrycode: "RW", country: "Rwanda", tz: "Africa/Kigali", offset: "UTC +02:00" },
            "Indian/Reunion": { id: "Indian/Reunion", countrycode: "RE", country: "Réunion", tz: "Indian/Reunion", offset: "UTC +04:00" },
            "America/St_Barthelemy": { id: "America/St_Barthelemy", countrycode: "BL", country: "Saint Barthélemy", tz: "America/St_Barthelemy", offset: "UTC -04:00" },
            "Atlantic/St_Helena": { id: "Atlantic/St_Helena", countrycode: "SH", country: "Saint Helena, Ascension and Tristan da Cunha", tz: "Atlantic/St_Helena", offset: "UTC" },
            "America/St_Kitts": { id: "America/St_Kitts", countrycode: "KN", country: "Saint Kitts and Nevis", tz: "America/St_Kitts", offset: "UTC -04:00" },
            "America/St_Lucia": { id: "America/St_Lucia", countrycode: "LC", country: "Saint Lucia", tz: "America/St_Lucia", offset: "UTC -04:00" },
            "America/Marigot": { id: "America/Marigot", countrycode: "MF", country: "Saint Martin (French part)", tz: "America/Marigot", offset: "UTC -04:00" },
            "America/Miquelon": { id: "America/Miquelon", countrycode: "PM", country: "Saint Pierre and Miquelon", tz: "America/Miquelon", offset: "UTC -03:00" },
            "America/St_Vincent": { id: "America/St_Vincent", countrycode: "VC", country: "Saint Vincent and the Grenadines", tz: "America/St_Vincent", offset: "UTC -04:00" },
            "Pacific/Apia": { id: "Pacific/Apia", countrycode: "WS", country: "Samoa", tz: "Pacific/Apia", offset: "UTC +14:00" },
            "Europe/San_Marino": { id: "Europe/San_Marino", countrycode: "SM", country: "San Marino", tz: "Europe/San_Marino", offset: "UTC +01:00" },
            "Africa/Sao_Tome": { id: "Africa/Sao_Tome", countrycode: "ST", country: "Sao Tome and Principe", tz: "Africa/Sao_Tome", offset: "UTC" },
            "Asia/Riyadh": { id: "Asia/Riyadh", countrycode: "SA", country: "Saudi Arabia", tz: "Asia/Riyadh", offset: "UTC +03:00" },
            "Africa/Dakar": { id: "Africa/Dakar", countrycode: "SN", country: "Senegal", tz: "Africa/Dakar", offset: "UTC" },
            "Europe/Belgrade": { id: "Europe/Belgrade", countrycode: "RS", country: "Serbia", tz: "Europe/Belgrade", offset: "UTC +01:00" },
            "Indian/Mahe": { id: "Indian/Mahe", countrycode: "SC", country: "Seychelles", tz: "Indian/Mahe", offset: "UTC +04:00" },
            "Africa/Freetown": { id: "Africa/Freetown", countrycode: "SL", country: "Sierra Leone", tz: "Africa/Freetown", offset: "UTC" },
            "Asia/Singapore": { id: "Asia/Singapore", countrycode: "SG", country: "Singapore", tz: "Asia/Singapore", offset: "UTC +08:00" },
            "America/Lower_Princes": { id: "America/Lower_Princes", countrycode: "SX", country: "Sint Maarten (Dutch part)", tz: "America/Lower_Princes", offset: "UTC -04:00" },
            "Europe/Bratislava": { id: "Europe/Bratislava", countrycode: "SK", country: "Slovakia", tz: "Europe/Bratislava", offset: "UTC +01:00" },
            "Europe/Ljubljana": { id: "Europe/Ljubljana", countrycode: "SI", country: "Slovenia", tz: "Europe/Ljubljana", offset: "UTC +01:00" },
            "Pacific/Guadalcanal": { id: "Pacific/Guadalcanal", countrycode: "SB", country: "Solomon Islands", tz: "Pacific/Guadalcanal", offset: "UTC +11:00" },
            "Africa/Mogadishu": { id: "Africa/Mogadishu", countrycode: "SO", country: "Somalia", tz: "Africa/Mogadishu", offset: "UTC +03:00" },
            "Africa/Johannesburg": { id: "Africa/Johannesburg", countrycode: "ZA", country: "South Africa", tz: "Africa/Johannesburg", offset: "UTC +02:00" },
            "Atlantic/South_Georgia": { id: "Atlantic/South_Georgia", countrycode: "GS", country: "South Georgia and the South Sandwich Islands", tz: "Atlantic/South_Georgia", offset: "UTC -02:00" },
            "Africa/Juba": { id: "Africa/Juba", countrycode: "SS", country: "South Sudan", tz: "Africa/Juba", offset: "UTC +03:00" },
            "Africa/Ceuta": { id: "Africa/Ceuta", countrycode: "ES", country: "Spain", tz: "Africa/Ceuta", offset: "UTC +01:00" },
            "Atlantic/Canary": { id: "Atlantic/Canary", countrycode: "ES", country: "Spain", tz: "Atlantic/Canary", offset: "UTC" },
            "Europe/Madrid": { id: "Europe/Madrid", countrycode: "ES", country: "Spain", tz: "Europe/Madrid", offset: "UTC +01:00" },
            "Asia/Colombo": { id: "Asia/Colombo", countrycode: "LK", country: "Sri Lanka", tz: "Asia/Colombo", offset: "UTC +05:30" },
            "Africa/Khartoum": { id: "Africa/Khartoum", countrycode: "SD", country: "Sudan", tz: "Africa/Khartoum", offset: "UTC +02:00" },
            "America/Paramaribo": { id: "America/Paramaribo", countrycode: "SR", country: "Suriname", tz: "America/Paramaribo", offset: "UTC -03:00" },
            "Arctic/Longyearbyen": { id: "Arctic/Longyearbyen", countrycode: "SJ", country: "Svalbard and Jan Mayen", tz: "Arctic/Longyearbyen", offset: "UTC +01:00" },
            "Africa/Mbabane": { id: "Africa/Mbabane", countrycode: "SZ", country: "Swaziland", tz: "Africa/Mbabane", offset: "UTC +02:00" },
            "Europe/Stockholm": { id: "Europe/Stockholm", countrycode: "SE", country: "Sweden", tz: "Europe/Stockholm", offset: "UTC +01:00" },
            "Europe/Zurich": { id: "Europe/Zurich", countrycode: "CH", country: "Switzerland", tz: "Europe/Zurich", offset: "UTC +01:00" },
            "Asia/Damascus": { id: "Asia/Damascus", countrycode: "SY", country: "Syrian Arab Republic", tz: "Asia/Damascus", offset: "UTC +02:00" },
            "Asia/Taipei": { id: "Asia/Taipei", countrycode: "TW", country: "Taiwan, Province of China", tz: "Asia/Taipei", offset: "UTC +08:00" },
            "Asia/Dushanbe": { id: "Asia/Dushanbe", countrycode: "TJ", country: "Tajikistan", tz: "Asia/Dushanbe", offset: "UTC +05:00" },
            "Africa/Dar_es_Salaam": { id: "Africa/Dar_es_Salaam", countrycode: "TZ", country: "Tanzania, United Republic of", tz: "Africa/Dar_es_Salaam", offset: "UTC +03:00" },
            "Asia/Bangkok": { id: "Asia/Bangkok", countrycode: "TH", country: "Thailand", tz: "Asia/Bangkok", offset: "UTC +07:00" },
            "Asia/Dili": { id: "Asia/Dili", countrycode: "TL", country: "Timor-Leste", tz: "Asia/Dili", offset: "UTC +09:00" },
            "Africa/Lome": { id: "Africa/Lome", countrycode: "TG", country: "Togo", tz: "Africa/Lome", offset: "UTC" },
            "Pacific/Fakaofo": { id: "Pacific/Fakaofo", countrycode: "TK", country: "Tokelau", tz: "Pacific/Fakaofo", offset: "UTC +13:00" },
            "Pacific/Tongatapu": { id: "Pacific/Tongatapu", countrycode: "TO", country: "Tonga", tz: "Pacific/Tongatapu", offset: "UTC +13:00" },
            "America/Port_of_Spain": { id: "America/Port_of_Spain", countrycode: "TT", country: "Trinidad and Tobago", tz: "America/Port_of_Spain", offset: "UTC -04:00" },
            "Africa/Tunis": { id: "Africa/Tunis", countrycode: "TN", country: "Tunisia", tz: "Africa/Tunis", offset: "UTC +01:00" },
            "Europe/Istanbul": { id: "Europe/Istanbul", countrycode: "TR", country: "Turkey", tz: "Europe/Istanbul", offset: "UTC +03:00" },
            "Asia/Ashgabat": { id: "Asia/Ashgabat", countrycode: "TM", country: "Turkmenistan", tz: "Asia/Ashgabat", offset: "UTC +05:00" },
            "America/Grand_Turk": { id: "America/Grand_Turk", countrycode: "TC", country: "Turks and Caicos Islands", tz: "America/Grand_Turk", offset: "UTC -05:00" },
            "Pacific/Funafuti": { id: "Pacific/Funafuti", countrycode: "TV", country: "Tuvalu", tz: "Pacific/Funafuti", offset: "UTC +12:00" },
            "Africa/Kampala": { id: "Africa/Kampala", countrycode: "UG", country: "Uganda", tz: "Africa/Kampala", offset: "UTC +03:00" },
            "Europe/Kiev": { id: "Europe/Kiev", countrycode: "UA", country: "Ukraine", tz: "Europe/Kiev", offset: "UTC +02:00" },
            "Europe/Simferopol": { id: "Europe/Simferopol", countrycode: "UA", country: "Ukraine", tz: "Europe/Simferopol", offset: "UTC +03:00" },
            "Europe/Uzhgorod": { id: "Europe/Uzhgorod", countrycode: "UA", country: "Ukraine", tz: "Europe/Uzhgorod", offset: "UTC +02:00" },
            "Europe/Zaporozhye": { id: "Europe/Zaporozhye", countrycode: "UA", country: "Ukraine", tz: "Europe/Zaporozhye", offset: "UTC +02:00" },
            "Asia/Dubai": { id: "Asia/Dubai", countrycode: "AE", country: "United Arab Emirates", tz: "Asia/Dubai", offset: "UTC +04:00" },
            "Europe/London": { id: "Europe/London", countrycode: "GB", country: "United Kingdom", tz: "Europe/London", offset: "UTC" },
            "America/Adak": { id: "America/Adak", countrycode: "US", country: "United States", tz: "America/Adak", offset: "UTC -10:00" },
            "America/Anchorage": { id: "America/Anchorage", countrycode: "US", country: "United States", tz: "America/Anchorage", offset: "UTC -09:00" },
            "America/Boise": { id: "America/Boise", countrycode: "US", country: "United States", tz: "America/Boise", offset: "UTC -07:00" },
            "America/Chicago": { id: "America/Chicago", countrycode: "US", country: "United States", tz: "America/Chicago", offset: "UTC -06:00" },
            "America/Denver": { id: "America/Denver", countrycode: "US", country: "United States", tz: "America/Denver", offset: "UTC -07:00" },
            "America/Detroit": { id: "America/Detroit", countrycode: "US", country: "United States", tz: "America/Detroit", offset: "UTC -05:00" },
            "America/Indiana/Indianapolis": { id: "America/Indiana/Indianapolis", countrycode: "US", country: "United States", tz: "America/Indiana/Indianapolis", offset: "UTC -05:00" },
            "America/Indiana/Knox": { id: "America/Indiana/Knox", countrycode: "US", country: "United States", tz: "America/Indiana/Knox", offset: "UTC -06:00" },
            "America/Indiana/Marengo": { id: "America/Indiana/Marengo", countrycode: "US", country: "United States", tz: "America/Indiana/Marengo", offset: "UTC -05:00" },
            "America/Indiana/Petersburg": { id: "America/Indiana/Petersburg", countrycode: "US", country: "United States", tz: "America/Indiana/Petersburg", offset: "UTC -05:00" },
            "America/Indiana/Tell_City": { id: "America/Indiana/Tell_City", countrycode: "US", country: "United States", tz: "America/Indiana/Tell_City", offset: "UTC -06:00" },
            "America/Indiana/Vevay": { id: "America/Indiana/Vevay", countrycode: "US", country: "United States", tz: "America/Indiana/Vevay", offset: "UTC -05:00" },
            "America/Indiana/Vincennes": { id: "America/Indiana/Vincennes", countrycode: "US", country: "United States", tz: "America/Indiana/Vincennes", offset: "UTC -05:00" },
            "America/Indiana/Winamac": { id: "America/Indiana/Winamac", countrycode: "US", country: "United States", tz: "America/Indiana/Winamac", offset: "UTC -05:00" },
            "America/Juneau": { id: "America/Juneau", countrycode: "US", country: "United States", tz: "America/Juneau", offset: "UTC -09:00" },
            "America/Kentucky/Louisville": { id: "America/Kentucky/Louisville", countrycode: "US", country: "United States", tz: "America/Kentucky/Louisville", offset: "UTC -05:00" },
            "America/Kentucky/Monticello": { id: "America/Kentucky/Monticello", countrycode: "US", country: "United States", tz: "America/Kentucky/Monticello", offset: "UTC -05:00" },
            "America/Los_Angeles": { id: "America/Los_Angeles", countrycode: "US", country: "United States", tz: "America/Los_Angeles", offset: "UTC -08:00" },
            "America/Menominee": { id: "America/Menominee", countrycode: "US", country: "United States", tz: "America/Menominee", offset: "UTC -06:00" },
            "America/Metlakatla": { id: "America/Metlakatla", countrycode: "US", country: "United States", tz: "America/Metlakatla", offset: "UTC -09:00" },
            "America/New_York": { id: "America/New_York", countrycode: "US", country: "United States", tz: "America/New_York", offset: "UTC -05:00" },
            "America/Nome": { id: "America/Nome", countrycode: "US", country: "United States", tz: "America/Nome", offset: "UTC -09:00" },
            "America/North_Dakota/Beulah": { id: "America/North_Dakota/Beulah", countrycode: "US", country: "United States", tz: "America/North_Dakota/Beulah", offset: "UTC -06:00" },
            "America/North_Dakota/Center": { id: "America/North_Dakota/Center", countrycode: "US", country: "United States", tz: "America/North_Dakota/Center", offset: "UTC -06:00" },
            "America/North_Dakota/New_Salem": { id: "America/North_Dakota/New_Salem", countrycode: "US", country: "United States", tz: "America/North_Dakota/New_Salem", offset: "UTC -06:00" },
            "America/Phoenix": { id: "America/Phoenix", countrycode: "US", country: "United States", tz: "America/Phoenix", offset: "UTC -07:00" },
            "America/Sitka": { id: "America/Sitka", countrycode: "US", country: "United States", tz: "America/Sitka", offset: "UTC -09:00" },
            "America/Yakutat": { id: "America/Yakutat", countrycode: "US", country: "United States", tz: "America/Yakutat", offset: "UTC -09:00" },
            "Pacific/Honolulu": { id: "Pacific/Honolulu", countrycode: "US", country: "United States", tz: "Pacific/Honolulu", offset: "UTC -10:00" },
            "Pacific/Midway": { id: "Pacific/Midway", countrycode: "UM", country: "United States Minor Outlying Islands", tz: "Pacific/Midway", offset: "UTC -11:00" },
            "Pacific/Wake": { id: "Pacific/Wake", countrycode: "UM", country: "United States Minor Outlying Islands", tz: "Pacific/Wake", offset: "UTC +12:00" },
            "America/Montevideo": { id: "America/Montevideo", countrycode: "UY", country: "Uruguay", tz: "America/Montevideo", offset: "UTC -03:00" },
            "Asia/Samarkand": { id: "Asia/Samarkand", countrycode: "UZ", country: "Uzbekistan", tz: "Asia/Samarkand", offset: "UTC +05:00" },
            "Asia/Tashkent": { id: "Asia/Tashkent", countrycode: "UZ", country: "Uzbekistan", tz: "Asia/Tashkent", offset: "UTC +05:00" },
            "Pacific/Efate": { id: "Pacific/Efate", countrycode: "VU", country: "Vanuatu", tz: "Pacific/Efate", offset: "UTC +11:00" },
            "America/Caracas": { id: "America/Caracas", countrycode: "VE", country: "Venezuela, Bolivarian Republic of", tz: "America/Caracas", offset: "UTC -04:00" },
            "Asia/Ho_Chi_Minh": { id: "Asia/Ho_Chi_Minh", countrycode: "VN", country: "Viet Nam", tz: "Asia/Ho_Chi_Minh", offset: "UTC +07:00" },
            "America/Tortola": { id: "America/Tortola", countrycode: "VG", country: "Virgin Islands, British", tz: "America/Tortola", offset: "UTC -04:00" },
            "America/St_Thomas": { id: "America/St_Thomas", countrycode: "VI", country: "Virgin Islands, U.S.", tz: "America/St_Thomas", offset: "UTC -04:00" },
            "Pacific/Wallis": { id: "Pacific/Wallis", countrycode: "WF", country: "Wallis and Futuna", tz: "Pacific/Wallis", offset: "UTC +12:00" },
            "Africa/El_Aaiun": { id: "Africa/El_Aaiun", countrycode: "EH", country: "Western Sahara", tz: "Africa/El_Aaiun", offset: "UTC +01:00" },
            "Asia/Aden": { id: "Asia/Aden", countrycode: "YE", country: "Yemen", tz: "Asia/Aden", offset: "UTC +03:00" },
            "Africa/Lusaka": { id: "Africa/Lusaka", countrycode: "ZM", country: "Zambia", tz: "Africa/Lusaka", offset: "UTC +02:00" },
            "Africa/Harare": { id: "Africa/Harare", countrycode: "ZW", country: "Zimbabwe", tz: "Africa/Harare", offset: "UTC +02:00" },
            "Europe/Mariehamn": { id: "Europe/Mariehamn", countrycode: "AX", country: "Åland Islands", tz: "Europe/Mariehamn", offset: "UTC +02:00" },
        }
    }

    /**
     * Get a specific timezone def by its code
     * @param code the code to get
     * @return {*} the tz definition, or null
     */
    static get(code) {
        return TimezoneDB.MAP[code];
    }

    /**
     * Get a list of timezones
     * @return {Array} an array of timezone object definitions
     */
    static list() {
        let list = [];
        for (let c of Object.values(TimezoneDB.MAP)) {
            list.push(c);
        }
        list.sort(function(a,b){
            if (a.id > b.id){ return 1 }
            if (a.id < b.id){ return -1 }
            return 0;
        });
        return list;
    }
    
}